title: Onik Lab.
description: Various IT-based research space, django, cloud, machine learning, and so on.

url: http://amanokaze.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

comments:
  provider : "onikaze"
  discus:
    shortname : "amanokaze-github-io"    

social:
  github: amanokaze
  facebook: oniamano
  email: oniamano@gmail.com

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true  

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: true
      related: false      

google_analytics: "UA-85642571-4"
