title: Onik Lab.
description: Various IT-based research space, django, cloud, machine learning, and so on.

url: http://amanokaze.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: amanokaze
  facebook: oniamano
  email: oniamano@gmail.com

google_analytics: "UA-85642571-4"
