title: Onik Lab.
description: Various IT-based research space, django, cloud, machine learning, and so on.

url: https://amanokaze.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/
encoding: UTF-8

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Books
    url: /books
  - title: Categories
    url: /categories
  - title: Articles
    url: /articles

comments:
  provider : "disqus"
  disqus:
    shortname : "onikaze"    

social:
  github: amanokaze
  facebook: oniamano
  email: oniamano@gmail.com

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true      

plugins:
  - jekyll-polyglot

languages: ['ko','en']
default_lang: 'ko'
exclude_from_localization: ['javascript','images','css']
parallel_localization: false

google_analytics: "UA-85642571-4"

gems:
  - jekyll-sitemap
  - jekyll-polyglot
   